### ISSUE TITLE
Exact match trigger

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#1]
https://app.rainforestqa.com/tests/300555

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- add new trigger, type: exact match
- put pattern: `This is a test trigger! I'm looking for a reaction.`
- put code: `cecho("\n<green>exact match trigger matched!")`
- back in main window, put in main input line: ``` `echo This is a test trigger! I'm looking for a reaction.```
- assert trigger response is shown
