### ISSUE TITLE
Simple command send alias

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#18]
https://app.rainforestqa.com/tests/300557

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- add new alias
- put pattern: `^buff(?: (\w+))?$`
- put code: `send("cast buff on "..(matches[2] or "myself"))`
- back in main window, put in main input line: `buff`
- assert alias response is `cast buff on myself`
- put in main input line: `buff Mudlet`
- assert alias response is `cast buff on Mudlet`
