### ISSUE TITLE
Regex trigger

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#2]
https://app.rainforestqa.com/tests/300328

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- add new trigger, type: regex
- put pattern: `^You give \w+ (\d+) coins?\.$`
- put code: `cecho(f"\n<green>FYI: gave away {matches[2]} coins.")`
- back in main window, put in main input line: ``` `echo You give Alice 5 coins.```
- assert trigger response is shown
