### ISSUE TITLE
Reconnect buttons

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#24]
https://app.rainforestqa.com/tests/300406

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- Start Mudlet, open random profile in Offline mode
- Click button: Reconnect
- Assert connection message is shown: `A connection has been established successfully.`
- Disconnect and clear output -- use `lua disconnect(); clearWindow()` for good measure 😄 
- Click menu: Games -> Reconnect
- Assert connection message is shown: `A connection has been established successfully.`
