### ISSUE TITLE
Simple command send trigger

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#3]
https://app.rainforestqa.com/tests/300321

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- add new trigger, type: exact match
- put pattern: `I'm a line! Trigger on me!`
- put command: `say OK, TRIGGERED!`
- back in main window, put in main input line: ``` `echo I'm a line! Trigger on me!```
- assert trigger response is shown
