### ISSUE TITLE
Start of line trigger

### ISSUE THREAD

**Issue by vadi2** [Mudlet/rainforest-planning#4]
https://app.rainforestqa.com/tests/300376

(requires a free login, let me know if you'd like access!)

**Comment by Kebap** [comment]
- add new trigger, type: start of line
- put pattern: `Start of line...`
- put code: `cecho("\n<green>start of line trigger matched!")`
- back in main window, put in main input line: ``` `echo Start of line... middle of line... end of line```
- assert trigger response is shown
